# Auto-generated by granger.py
# Date: 2025-04-25 14:17:47

top_indicators = [
    'TED_Spread',
    '10Y_Treasury',
    'Leading_Economic_Index',
    'Initial_Jobless_Claims',
    'Capacity_Utilization',
    'Industrial_Production_Index',
    'Core_CPI',
    'Exports_(Goods_&_Services)',
    'PCE_Price_Index',
    'CPI_(All_Items)',
    'High_Yield_Spread_(ICE_BofA)',
    '2Y_Treasury',
    'Personal_Consumption_Expenditures',

]
selected_indicators = [
    'TED_Spread', '10Y_Treasury', 'Leading_Economic_Index', 'Initial_Jobless_Claims',
    'Capacity_Utilization', 'Industrial_Production_Index', 'Core_CPI',
    'Exports_(Goods_&_Services)', 'PCE_Price_Index', 'CPI_(All_Items)',
    'High_Yield_Spread_(ICE_BofA)', '2Y_Treasury', 'Personal_Consumption_Expenditures',
    'PPI_(All_Commodities)', 'BAA_Corporate_Bond_Yield_Bond_BAA_Yield_Volatility'
]
